"""Remove source_url from Flashcard model

Revision ID: 62a48643fe65
Revises: 1a59f2accada
Create Date: 2025-06-13 13:45:20.794038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a48643fe65'
down_revision: Union[str, None] = '1a59f2accada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'source_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
