"""Add image_url to deck model

Revision ID: 73a0edeeb962
Revises: 6a8ec83a9527
Create Date: 2025-06-29 14:50:11.881286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a0edeeb962'
down_revision: Union[str, None] = '6a8ec83a9527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'image_url')
    # ### end Alembic commands ###
