"""add source_url to flashcard model

Revision ID: 73ea07d54d0e
Revises: 71bef21a70df
Create Date: 2025-06-13 13:35:45.871264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ea07d54d0e'
down_revision: Union[str, None] = '71bef21a70df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'source_url')
    # ### end Alembic commands ###
