"""Add Deck model and link flashcards to decks

Revision ID: 88f16a04415c
Revises: 6ce699912762
Create Date: 2025-06-13 11:02:58.957316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f16a04415c'
down_revision: Union[str, None] = '6ce699912762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
