"""Add SMS opt-in field to User model

Revision ID: a0cfd5da05f6
Revises: 73a0edeeb962
Create Date: 2025-08-08 11:17:10.129374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0cfd5da05f6'
down_revision: Union[str, None] = '73a0edeeb962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sms_opt_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_opt_in')
    # ### end Alembic commands ###
