"""Add Google OAuth support to User model

Revision ID: b1c2d3e4f5g6
Revises: a0cfd5da05f6
Create Date: 2025-01-06 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5g6'
down_revision: Union[str, None] = 'a0cfd5da05f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add google_id column (nullable for existing users)
    op.add_column('users', sa.Column('google_id', sa.String(255), nullable=True))
    
    # Make password_hash nullable (existing users keep their passwords)
    op.alter_column('users', 'password_hash', nullable=True)
    
    # Make phone_number nullable (existing users keep their phone numbers)
    op.alter_column('users', 'phone_number', nullable=True)
    
    # Create index on google_id for performance
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the index first
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    
    # Drop google_id column
    op.drop_column('users', 'google_id')
    
    # Revert password_hash to not nullable (this might fail if there are Google users)
    # op.alter_column('users', 'password_hash', nullable=False)
    
    # Revert phone_number to not nullable (this might fail if there are Google users)
    # op.alter_column('users', 'phone_number', nullable=False)
    # ### end Alembic commands ###
