"""Add auth fields

Revision ID: eacc1499b943
Revises: 
Create Date: 2025-06-11 09:58:03.865744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacc1499b943'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add columns as nullable
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # 2. Populate existing rows with unique placeholder emails
    op.execute("UPDATE users SET email = 'placeholder+' || id || '@example.com' WHERE email IS NULL")
    op.execute("UPDATE users SET password_hash = 'changeme' WHERE password_hash IS NULL")
    # 3. Alter columns to be non-nullable
    op.alter_column('users', 'email', nullable=False)
    op.alter_column('users', 'password_hash', nullable=False)
    # 4. Create index
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
